@startuml
autonumber
skinparam style strictuml

actor Karyawan
boundary "Mobile App Android" as Form
control "Control Keamanan" as Ctrl
entity "Server Absensi" as DB

activate Form
Form -> Ctrl: Mengakses kamera depan dan layanan GPS
activate Ctrl
Ctrl -> Ctrl: Melakukan pemeriksaan integritas OS Android

alt [Perangkat Rooted / Dimodifikasi / Ya]
    Ctrl --> Form: Menolak proses absensi
    Form --> Karyawan: Menampilkan pesan peringatan modifikasi
    Form -> Form: Menghentikan akses ke fitur presensi
else [Perangkat Aman / Tidak]
    Ctrl --> Form: Sistem aman
    deactivate Ctrl
    
    activate Karyawan
    Karyawan -> Form: Mengambil foto selfie sebagai bukti
    Form -> Ctrl: Meneruskan foto, GPS, dan info perangkat
    activate Ctrl
    Ctrl -> Ctrl: Menggabungkan foto, koordinat, dan identitas perangkat
    Ctrl -> DB: Mengirimkan paket data absensi ke server
    activate DB
    DB --> Ctrl: Memvalidasi & Menerima data
    DB --> Ctrl: Mengembalikan konfirmasi keberhasilan
    deactivate DB
    Ctrl --> Form: Meneruskan konfirmasi keberhasilan
    Form --> Karyawan: Menampilkan notifikasi presensi sukses
end

deactivate Ctrl
deactivate Form
deactivate Karyawan
@enduml