/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.PengerjaanDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Pengerjaan;

import model.Pengerjaan;

import javax.swing.JOptionPane;

/**
 *
 * @author : Purwa | Andrian M.D
 *
 * Created : 28 Jun 2026
 */
public class DashboardAdminFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAdminFrame.class.getName());

    private String namaUserAktif;
    private PengerjaanDAO pengerjaanDAO = new PengerjaanDAO();

    /**
     * Creates new form DashboardAdminFrame
     */
    public DashboardAdminFrame(String nama) {
        initComponents();
        this.namaUserAktif = nama;

        this.setTitle("Dashboard Hak Akses Level 1 - " + namaUserAktif);
        loadDataTabel();
    }

    public void loadDataTabel() {
        DefaultTableModel model = (DefaultTableModel) tabelHasil.getModel();
        model.setRowCount(0);

        // Ambil data yang HANYA dimiliki oleh user yang sedang login
        List<Pengerjaan> daftarPengerjaan = pengerjaanDAO.ambilSemuaHasil();

        for (Pengerjaan p : daftarPengerjaan) {
            Object[] row = {
                p.getIdPengerjaan(),
                p.getPengguna(),
                p.getSkor(),
                p.getTanggalPengerjaan(),
                p.getJamPengerjaan()
            };
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelHasil = new javax.swing.JTable();
        btnUbah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnHapus = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID pengerjaan", "Pengguna", "Skor", "Tanggal", "Jam"
            }
        ));
        jScrollPane1.setViewportView(tabelHasil);

        btnUbah.setBackground(new java.awt.Color(204, 102, 0));
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Edit");
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DASHBOARD ADMIN");

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btn_logout.setBackground(new java.awt.Color(255, 0, 0));
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Log out");
        btn_logout.addActionListener(this::btn_logoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int barisTerpilih = tabelHasil.getSelectedRow();
        if (barisTerpilih == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus terlebih dahulu di tabel!");
            return;
        }

        // 2. Ambil ID Pengerjaan dari kolom pertama (index 0) pada baris yang dipilih
        int idPengerjaan = (int) tabelHasil.getValueAt(barisTerpilih, 0);

        // 3. Tampilkan dialog konfirmasi
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);

        // 4. Jika user klik "Yes", eksekusi fungsi DAO
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            if (pengerjaanDAO.hapusPengerjaan(idPengerjaan)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                loadDataTabel(); // Refresh tabel agar data yang terhapus hilang dari layar
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data!");
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        int barisTerpilih = tabelHasil.getSelectedRow();
        if (barisTerpilih == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah terlebih dahulu di tabel!");
            return;
        }

        // 2. Ambil ID Pengerjaan dan Skor Lama dari tabel
        int idPengerjaan = (int) tabelHasil.getValueAt(barisTerpilih, 0);
        int skorLama = (int) tabelHasil.getValueAt(barisTerpilih, 2); // Skor ada di index kolom 2

        // 3. Tampilkan input dialog untuk memasukkan skor baru
        String inputSkorBaru = javax.swing.JOptionPane.showInputDialog(this, "Ubah Skor:", skorLama);

        // 4. Validasi dan eksekusi
        if (inputSkorBaru != null && !inputSkorBaru.trim().isEmpty()) {
            try {
                int skorBaru = Integer.parseInt(inputSkorBaru); // Pastikan inputan adalah angka
                if (pengerjaanDAO.ubahSkor(idPengerjaan, skorBaru)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Skor berhasil diperbarui!");
                    loadDataTabel(); // Refresh tabel
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengubah skor!");
                }
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: Skor harus berupa angka bulat!");
            }
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        LoginFrame p = new LoginFrame();
        p.setLocationRelativeTo(null);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelHasil;
    // End of variables declaration//GEN-END:variables

}
