/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.table.DefaultTableModel;
import dao.PengerjaanDAO;
import model.Pengerjaan;
import java.util.List;

/**
 *
 * @author : Purwa | Andrian M.D
 *
 * Created : 28 Jun 2026
 */
public class DashboardUserFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardUserFrame.class.getName());

    private String namaUserAktif;
    private PengerjaanDAO pengerjaanDAO = new PengerjaanDAO();

    private java.util.List<String> operatorSelesai = new java.util.ArrayList<>();
    private int totalSkorUjian = 0;

    /**
     * Creates new form DashboardUserFrame
     */
    public DashboardUserFrame(String nama) {
        initComponents();
        this.namaUserAktif = nama;

        this.setTitle("Dashboard Hak Akses Level 2 - " + namaUserAktif);
        lbl_status_ujian.setText("Status: 4 tipe soal belum dikerjakan");

        javax.swing.JOptionPane.showMessageDialog(this,
                "Mode Testing Aktif!\n"
                + "Tombol Logout tidak akan menutup dashboard ini.\n"
                + "Gunakan ini untuk login akun lain secara bersamaan\n"
                + "dan mengetes fitur anti-tabrak soal antar user.",
                "Info Pengembang",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        loadDataTabel();
    }

    public void loadDataTabel() {
        DefaultTableModel model = (DefaultTableModel) tabelHasil.getModel();
        model.setRowCount(0);

        // Ambil data yang HANYA dimiliki oleh user yang sedang login
        List<Pengerjaan> daftarPengerjaan = pengerjaanDAO.ambilHasilPerUser(namaUserAktif);

        for (Pengerjaan p : daftarPengerjaan) {
            Object[] row = {
                p.getIdPengerjaan(),
                p.getPengguna(),
                p.getSkor(),
                p.getTanggalPengerjaan(),
                p.getJamPengerjaan()
            };
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelHasil = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cb_operator = new javax.swing.JComboBox<>();
        Keluar = new javax.swing.JButton();
        lbl_status_ujian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelHasil);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DASHBOARD USER");

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Mulai Latihan");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        cb_operator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/" }));

        Keluar.setBackground(new java.awt.Color(153, 0, 0));
        Keluar.setForeground(new java.awt.Color(255, 255, 255));
        Keluar.setText("Log out");
        Keluar.addActionListener(this::KeluarActionPerformed);

        lbl_status_ujian.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_operator, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_status_ujian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_operator, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_status_ujian, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String operatorPilihan = cb_operator.getSelectedItem().toString();

        // 1. Cek apakah operator ini sudah dikerjakan sebelumnya
        if (operatorSelesai.contains(operatorPilihan)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kamu sudah menyelesaikan soal " + operatorPilihan + "! Silakan pilih operator lain.");
            return;
        }

        // 2. Coba kunci operatornya
        if (pengerjaanDAO.kunciOperator(operatorPilihan, namaUserAktif)) {

            // HIDE dashboard (jangan dispose), lalu kirim 'this' (diri sendiri) ke QuizFrame
            QuizFrame kuis = new QuizFrame(namaUserAktif, operatorPilihan, this);
            kuis.setLocationRelativeTo(null);
            kuis.setVisible(true);
            this.setVisible(false);

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Maaf, soal " + operatorPilihan + " sedang dikerjakan oleh orang lain. Tunggu sebentar atau pilih soal lain!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        LoginFrame p = new LoginFrame();
        p.setLocationRelativeTo(null);
        p.setVisible(true);

    }//GEN-LAST:event_KeluarActionPerformed

    public void selesaiSesiOperator(String operator, int skorSesi) {
        operatorSelesai.add(operator);
        totalSkorUjian += skorSesi;

        // 1. Hapus operator yang sudah beres dari ComboBox agar tidak bisa dipilih lagi
        cb_operator.removeItem(operator);

        int sisa = 4 - operatorSelesai.size();

        if (operatorSelesai.size() == 4) {
            lbl_status_ujian.setText("Status: Semua ujian selesai!");
            javax.swing.JOptionPane.showMessageDialog(this, "Selamat! Kamu telah menyelesaikan semua 4 tipe soal.\nTotal Skor Akhir: " + totalSkorUjian);

            // Simpan skor ke database
            pengerjaanDAO.simpanHasil(namaUserAktif, totalSkorUjian);
            loadDataTabel();

            // RESET SISTEM (Agar user bisa ikut ujian gelombang 2 jika mau)
            operatorSelesai.clear();
            totalSkorUjian = 0;
            lbl_status_ujian.setText("Status: 4 tipe soal belum dikerjakan");

            // Kembalikan isi ComboBox seperti semula
            cb_operator.removeAllItems();
            cb_operator.addItem("+");
            cb_operator.addItem("-");
            cb_operator.addItem("*");
            cb_operator.addItem("/");

            this.setVisible(true);
        } else {
            // 2. Update teks pemberitahuan sisa soal di Dashboard
            lbl_status_ujian.setText("Status: Sisa " + sisa + " tipe soal");
            javax.swing.JOptionPane.showMessageDialog(this, "Soal " + operator + " selesai!\nSisa tipe soal yang belum dikerjakan: " + sisa);
            this.setVisible(true);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Keluar;
    private javax.swing.JComboBox<String> cb_operator;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_status_ujian;
    private javax.swing.JTable tabelHasil;
    // End of variables declaration//GEN-END:variables

}
