/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.PengerjaanDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author : Purwa | Andrian M.D
 *
 * Created : 28 Jun 2026
 */
public class QuizFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuizFrame.class.getName());

    private String namaUserAktif;
    private int nomorSoal = 1;
    private int skor = 0;
    private String operatorKuis;
    private double jawabanBenar = 0;

    private int detikTersisa = 300; // 5 Menit = 300 Detik
    private Timer timerWaktu;

    private view.DashboardUserFrame dashboardAsal;

    /**
     * Creates new form QuizFrame
     */
    public QuizFrame(String nama, String operator, view.DashboardUserFrame dashboard) {
        initComponents();
        this.namaUserAktif = nama;
        this.operatorKuis = operator;
        this.dashboardAsal = dashboard;
        this.setTitle("Latihan Matematika - " + namaUserAktif);

        // Langsung generate soal pertama
        jalankanTimer();
        generateSoal();
    }

    private void jalankanTimer() {
        timerWaktu = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                detikTersisa--;
                int menit = detikTersisa / 60;
                int detik = detikTersisa % 60;

                // Update JLabel waktu di UI (Pastikan sudah buat lbl_waktu di NetBeans)
                lbl_waktu.setText(String.format("Waktu: %02d:%02d", menit, detik));

                if (detikTersisa <= 0) {
                    timerWaktu.stop();
                    JOptionPane.showMessageDialog(null, "Waktu Habis!");
                    selesaiKuis(); // Paksa selesai jika waktu habis
                }
            }
        });
        timerWaktu.start();
    }

    public void generateSoal() {
        tf_jawab.setText("");
        tf_jawab.requestFocus();

        Random rand = new Random();
        int angka1 = rand.nextInt(100) + 1;
        int angka2 = rand.nextInt(100) + 1;

        // KALKULASI KINI HANYA MENGGUNAKAN OPERATOR YANG DIPILIH
        switch (operatorKuis) {
            case "+":
                jawabanBenar = angka1 + angka2;
                break;
            case "-":
                jawabanBenar = angka1 - angka2;
                break;
            case "*":
                jawabanBenar = angka1 * angka2;
                break;
            case "/":
                jawabanBenar = (double) angka1 / angka2;
                break;
        }

        txtSoal.setText("Soal " + nomorSoal + "/10 : " + angka1 + " " + operatorKuis + " " + angka2 + " = ?");
    }

    private void selesaiKuis() {
        if (timerWaktu != null) {
            PengerjaanDAO dao = new PengerjaanDAO();
            dao.bukaKunciOperator(operatorKuis);

            // 2. Lempar skor kembali ke Dashboard (TIDAK ADA simpanHasil di sini)
            dashboardAsal.selesaiSesiOperator(operatorKuis, skor);

            // 3. Hancurkan frame kuis saja
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtSoal = new javax.swing.JLabel();
        tf_jawab = new javax.swing.JTextField();
        btn_jawab = new javax.swing.JButton();
        lbl_waktu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("QUIZ FORM");

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        txtSoal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSoal.setText("SOAL ; X + X ");

        tf_jawab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_jawabKeyPressed(evt);
            }
        });

        btn_jawab.setText("JAWAB");
        btn_jawab.addActionListener(this::btn_jawabActionPerformed);
        btn_jawab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_jawabKeyPressed(evt);
            }
        });

        lbl_waktu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_waktu.setText("00:00");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Enter Otomatis Jawab");

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_waktu)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(txtSoal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 103, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_jawab)
                            .addComponent(btn_jawab, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(txtSoal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_jawab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_jawab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_jawabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jawabActionPerformed
        // TODO add your handling code here:
        String input = tf_jawab.getText().trim();

        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi jawabanmu dulu!");
            return;
        }

        try {
            double jawabanUser = Double.parseDouble(input);

            // Cek kebenaran (toleransi desimal untuk pembagian)
            if (Math.abs(jawabanUser - jawabanBenar) < 0.01) {
                skor += 10;
            }

            // Cek apakah kuis sudah mencapai 10 soal
            if (nomorSoal == 10) {
                selesaiKuis();
            } else {
                nomorSoal++; // Lanjut ke soal berikutnya
                generateSoal();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan format angka yang valid!");
        }
    }//GEN-LAST:event_btn_jawabActionPerformed

    private void btn_jawabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_jawabKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_jawabKeyPressed

    private void tf_jawabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_jawabKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {

            btn_jawab.doClick(); // Mensimulasikan klik otomatis pada tombol btn_jawab

        }
    }//GEN-LAST:event_tf_jawabKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_jawab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_waktu;
    private javax.swing.JTextField tf_jawab;
    private javax.swing.JLabel txtSoal;
    // End of variables declaration//GEN-END:variables

}
