@startuml
skinparam packageStyle rectangle

actor HR
actor Karyawan
actor Sales

Karyawan <|-- Sales

rectangle "Sistem Absensi Internal Cifo" {

    usecase "Mendaftarkan Wajah & NIP" as UC_Daftar
    usecase "Mendeteksi Lokasi & Fake GPS" as UC_Deteksi

    usecase "Melakukan Presensi" as UC_Presensi

    ' Mengelompokkan anak-anak use case
    usecase "Presensi via Face Recognition" as UC_Face
    usecase "Presensi via Mobile App (Untuk Android)" as UC_App
    usecase "Presensi via Web (Untuk iOS)" as UC_Web

    ' REVISI: Arah panah DARI extension KE base case
    UC_App .down.> UC_Presensi : <<extend>>
    UC_Web .down.> UC_Presensi : <<extend>>
    UC_Face .down.> UC_Presensi : <<extend>>

    usecase "Melakukan Public Absen" as UC_PublicAbsen

    UC_App .down.> UC_PublicAbsen : <<extend>>
    UC_Web .down.> UC_PublicAbsen : <<extend>>
}

HR -- UC_Daftar
HR -- UC_Deteksi

Karyawan -right- UC_Presensi
Sales -right- UC_PublicAbsen

@enduml