@startuml
left to right direction
skinparam packageStyle rectangle

actor Sales
actor Teknisi
actor Logistik
actor Finance
actor NOC
actor "Customer Service" as CS

rectangle "Sistem Operasional Terintegrasi Cifo" {
    
    usecase "Mencatat Data Prospek Pelanggan" as UC_Visit
    
    usecase "Mengecek Ketersediaan Jaringan (ODP)" as UC_CekJaringan
    usecase "Mengajukan Pengambilan Perangkat" as UC_MintaBarang
    usecase "Menyiapkan Perangkat Instalasi" as UC_SiapBarang
    usecase "Melakukan Instalasi Fisik" as UC_Instalasi
    
    usecase "Memvalidasi Pembayaran Pemasangan" as UC_Validasi
    usecase "Mengaktifkan Akses Internet" as UC_Aktivasi
    
    usecase "Menerima Keluhan Pelanggan" as UC_Komplain
    
    ' Include: kegiatan yang diharuskan terjadi
    UC_Instalasi .> UC_MintaBarang : <<include>>
    UC_Aktivasi .> UC_Validasi : <<include>>
}

Sales -- UC_Visit

Teknisi -- UC_CekJaringan
Teknisi -- UC_MintaBarang
Teknisi -- UC_Instalasi

Logistik -- UC_SiapBarang

Finance -- UC_Validasi
NOC -- UC_Aktivasi

CS -- UC_Komplain
@enduml