@startuml
left to right direction
skinparam packageStyle rectangle

actor HRD
actor Karyawan
actor Sales

' Generalisasi Actor
Karyawan <|-- Sales

rectangle "Sistem Absensi Internal Cifo" {
    usecase "Mendaftarkan Wajah & NIP" as UC_Daftar
    usecase "Mengelola Pengecualian Absen" as UC_KelolaException
    
    usecase "Melakukan Presensi" as UC_Presensi
    usecase "Presensi via Web" as UC_Web
    usecase "Presensi via Mobile App" as UC_App
    usecase "Presensi via Face Detector" as UC_Face
    
    ' Generalisasi Use Case (Sesuai aturan dosen)
    UC_Presensi <|-- UC_Web
    UC_Presensi <|-- UC_App
    UC_Presensi <|-- UC_Face
    
    usecase "Mengajukan Public Absen" as UC_PublicAbsen
    
    ' Extend digunakan jika syarat tertentu terpenuhi (berada di luar kantor)
    UC_PublicAbsen .> UC_Presensi : <<extend>>
}

HRD -- UC_Daftar
HRD -- UC_KelolaException

Karyawan -- UC_Presensi
Sales -- UC_PublicAbsen
@enduml