@startuml
autonumber
skinparam style strictuml

actor Logistik
boundary "Dashboard Logistik" as Form
control "Controller Gudang" as Ctrl
entity "Database Gudang" as DB

activate Logistik
Logistik -> Form: Membuka daftar permintaan perangkat
activate Form
Form -> Ctrl: Meminta data stok perangkat
activate Ctrl
Ctrl -> DB: Mengecek ketersediaan stok
activate DB
DB --> Ctrl: Mengembalikan informasi stok yang tersedia
deactivate DB
Ctrl --> Form: Mengirimkan data stok
Form --> Logistik: Menampilkan informasi stok

alt [Stok tidak mencukupi / Tidak]
    Ctrl --> Form: Mengirimkan peringatan stok habis
    Form --> Logistik: Memberikan peringatan stok tidak cukup
    Logistik -> Form: Menunda proses penyerahan barang
else [Stok mencukupi / Ya]
    Logistik -> Logistik: Menyiapkan perangkat sesuai permintaan
    Logistik -> Form: Menyerahkan perangkat ke Teknisi & menekan konfirmasi
    
    Form -> Ctrl: Memproses penyerahan barang
    Ctrl -> Ctrl: Menjalankan proses pembaruan stok otomatis (Include UC_OP13)
    
    Ctrl -> DB: Memotong stok & Menandai permintaan selesai
    activate DB
    DB --> Ctrl: Konfirmasi update stok berhasil
    deactivate DB
    
    Ctrl --> Form: Status penyerahan sukses
    Form --> Logistik: Menampilkan notifikasi selesai
end

deactivate Ctrl
deactivate Form
deactivate Logistik
@enduml